### ISSUE TITLE
Sending Email using code

### ISSUE THREAD

**Issue by awillaum** [Haulmont/jmix-emailtemplates#22]
Hi,

I'm trying to send email but I have an error when I'm trying to call **buildFromTemplate**, here are the  stack trace :
`Caused by: java.lang.IllegalStateException: Cannot get unfetched attribute [html] from detached object io.jmix.emailtemplates.entity.JsonEmailTemplate-84ecaa87-f6fc-75c5-2b7f-18b610904946 [detached].
	at org.eclipse.persistence.internal.queries.EntityFetchGroup.onUnfetchedAttribute(EntityFetchGroup.java:100) ~[org.eclipse.persistence.core-2.7.9-4-jmix.jar:na]
	at io.jmix.eclipselink.impl.JmixEntityFetchGroup.onUnfetchedAttribute(JmixEntityFetchGroup.java:67) ~[jmix-eclipselink-1.1.0.jar:na]
	at org.eclipse.persistence.internal.jpa.EntityManagerImpl.processUnfetchedAttribute(EntityManagerImpl.java:3027) ~[org.eclipse.persistence.jpa-2.7.9-4-jmix.jar:na]
	at io.jmix.emailtemplates.entity.EmailTemplate._persistence_checkFetched(EmailTemplate.java) ~[jmix-emailtemplates-1.1.0.jar:na]
	at io.jmix.emailtemplates.entity.JsonEmailTemplate._persistence_get_html(JsonEmailTemplate.java) ~[jmix-emailtemplates-1.1.0.jar:na]
	at io.jmix.emailtemplates.entity.JsonEmailTemplate.getHtml(JsonEmailTemplate.java:51) ~[jmix-emailtemplates-1.1.0.jar:na]
	... 111 common frames omitted`

Second issue, I don't found the predefined roles  **email-templates-can-send-templates-core** and **email-templates-can-send-templates** that was mentioned in your documentation.

Best regards

**Comment by awillaum** [comment]
Caused by: java.lang.reflect.InvocationTargetException: null

Caused by: org.springframework.beans.FatalBeanException: Could not copy property 'html' from source to target; nested exception is java.lang.reflect.InvocationTargetException

Caused by: java.lang.reflect.InvocationTargetException: null

Caused by: java.lang.IllegalStateException: Cannot get unfetched attribute [html] from detached object io.jmix.emailtemplates.entity.JsonEmailTemplate-84ecaa87-f6fc-75c5-2b7f-18b610904946 [detached].

**Comment by lovtsovaik** [comment]
@gorbunkov please provide QA notes

**Comment by gorbunkov** [comment]
@lovtsovaik 
[EmailTemplate Builder](https://github.com/Haulmont/jmix-emailtemplates#41-email-templates-builder-) API that accepted template code didn't work. Something like this:

```java
EmailTemplate emailTemplate1 = emailTemplates.buildFromTemplate("<template_code>")
           .setSubject("...")
           .setTo("...")
           .build();
```

**Comment by lovtsovaik** [comment]
verified on Jmix version: 1.2.0-SNAPSHOT and 1.3.999-SNAPSHOT
